### ISSUE TITLE
ERR_OSSL_EVP_UNSUPPORTED

### ISSUE THREAD

**Issue by SHAX1PTb** [nabendu82/final-space-react#1]
pranavi.annigeri@Pranavis-Air final-space-react % npm run build

> final-space-react@0.1.0 build
> react-scripts build

Creating an optimized production build...
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:140:10)
    at module.exports (/Users/pranavi.annigeri/code/final-space-react/node_modules/webpack/lib/util/createHash.js:90:53)
    at NormalModule._initBuildHash (/Users/pranavi.annigeri/code/final-space-react/node_modules/webpack/lib/NormalModule.js:386:16)
    at handleParseError (/Users/pranavi.annigeri/code/final-space-react/node_modules/webpack/lib/NormalModule.js:434:10)
    at /Users/pranavi.annigeri/code/final-space-react/node_modules/webpack/lib/NormalModule.js:466:5
    at /Users/pranavi.annigeri/code/final-space-react/node_modules/webpack/lib/NormalModule.js:327:12
    at /Users/pranavi.annigeri/code/final-space-react/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/pranavi.annigeri/code/final-space-react/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/pranavi.annigeri/code/final-space-react/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /Users/pranavi.annigeri/code/final-space-react/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/Users/pranavi.annigeri/code/final-space-react/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/Users/pranavi.annigeri/code/final-space-react/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/Users/pranavi.annigeri/code/final-space-react/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/pranavi.annigeri/code/final-space-react/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Users/pranavi.annigeri/code/final-space-react/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
/Users/pranavi.annigeri/code/final-space-react/node_modules/react-scripts/scripts/build.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:140:10)
    at module.exports (/Users/pranavi.annigeri/code/final-space-react/node_modules/webpack/lib/util/createHash.js:90:53)
    at NormalModule._initBuildHash (/Users/pranavi.annigeri/code/final-space-react/node_modules/webpack/lib/NormalModule.js:386:16)
    at /Users/pranavi.annigeri/code/final-space-react/node_modules/webpack/lib/NormalModule.js:418:10
    at /Users/pranavi.annigeri/code/final-space-react/node_modules/webpack/lib/NormalModule.js:293:13
    at /Users/pranavi.annigeri/code/final-space-react/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/pranavi.annigeri/code/final-space-react/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/pranavi.annigeri/code/final-space-react/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/pranavi.annigeri/code/final-space-react/node_modules/babel-loader/lib/index.js:51:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v19.8.1

**Comment by hellosze** [comment]
I'm on to chapter 2 of this book Beginning React and Firebase: Create Four Beginner-Friendly Projects Using React and Firebase.
The way to fix this error is to modify scripts section of your package.json

"build" : "react-scripts --openssl-legacy-provider build"
